### ISSUE TITLE
Press ESC to reset window 

### ISSUE THREAD

**Issue by Matthes-Kdr** [Matthes-Kdr/pixel-ruler#3]
All lines should be cleared. 

Maybe the easyst way to achieve this is simply to restart the script itself . Or the code could be refactored into functions and the main function generate the root window...

**NOTE** pressing esc should not delete the currently stored scale factor and unit if desire !

**Comment by Roiquiem** [comment]
Hey, I created a pull request

**Comment by Matthes-Kdr** [comment]
Closed because of finishing - thanks to @Roiquiem 👍
